name: CI

on: 
  push:
    branches: 
    - "*"
  pull_request:
    branches: 
    - "*"

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build + Test
      run: swift test
      
  linux:
    strategy:
      matrix:
        image: ["swift:5.1", "swift:5.2"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build + Test
      run: swift test
